name: Verify Android
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Cache node_modules
        id: node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            test-app/node_modules
          key: node-modules
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            .gradle
            test-app/android/.gradle
            ~/.gradle/caches
          key: gradle
      - run: npm i
      - name: Build Plugin
        run: npm run build
      - name: Verify Android
        run: cd android && ./gradlew clean build test connectedAndroidTest
