# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Run Lint
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
permissions:
  id-token: write
  attestations: write
jobs:
  lint:
    runs-on: macos-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Cache node_modules
        id: node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            test-app/node_modules
          key: node-modules
      - name: Install Homebrew
        id: homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install swiftlint
        run: brew install swiftlint
      - run: npm i
      - run: npm run lint
      - run: npm pack
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: '${{ github.workspace }}/*.tgz'
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/*.tgz'
